<a href="https://colab.research.google.com/github/mdanyassri/Project-139/blob/main/Project_139.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.7/dist-packages (1.5.12)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.7/dist-packages (from kaggle) (2.8.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.7/dist-packages (from kaggle) (4.62.3)
Requirement already satisfied: certifi in /usr/local/lib/python3.7/dist-packages (from kaggle) (2021.10.8)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.7/dist-packages (from kaggle) (1.24.3)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from kaggle) (2.23.0)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.7/dist-packages (from kaggle) (1.15.0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.7/dist-packages (from kaggle) (6.0.1)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.7/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->kaggle) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->kaggle) (3.0.4)

In [2]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json

{'kaggle.json': b'{"username":"mdanyassri","key":"343651dfe286f542ee1d1f4e3f2dbe16"}'}

In [3]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/

!chmod 600 ~/.kaggle/kaggle.json

In [4]:
!kaggle datasets download -d gspmoreira/articles-sharing-reading-from-cit-deskdrop

Downloading articles-sharing-reading-from-cit-deskdrop.zip to /content
  0% 0.00/8.20M [00:00<?, ?B/s]
100% 8.20M/8.20M [00:00<00:00, 75.2MB/s]

In [5]:
!ls

articles-sharing-reading-from-cit-deskdrop.zip	kaggle.json  sample_data

In [6]:
!unzip articles-sharing-reading-from-cit-deskdrop.zip

Archive:  articles-sharing-reading-from-cit-deskdrop.zip
  inflating: shared_articles.csv
  inflating: users_interactions.csv

In [7]:
!ls

articles-sharing-reading-from-cit-deskdrop.zip	shared_articles.csv
kaggle.json					users_interactions.csv
sample_data

In [8]:
import pandas as pd 
import numpy as np 

df1=pd.read_csv('shared_articles.csv')
df2=pd.read_csv('users_interactions.csv')

In [9]:
df1.head(3)

    timestamp  ... lang
0  1459192779  ...   en
1  1459193988  ...   en
2  1459194146  ...   en

[3 rows x 13 columns]

In [10]:
df2.head(3)

    timestamp eventType  ...  userRegion  userCountry
0  1465413032      VIEW  ...         NaN          NaN
1  1465412560      VIEW  ...          NY           US
2  1465416190      VIEW  ...         NaN          NaN

[3 rows x 8 columns]

In [11]:
df1 = df1[df1['eventType'] == 'CONTENT SHARED']
df1.head(3)

    timestamp  ... lang
1  1459193988  ...   en
2  1459194146  ...   en
3  1459194474  ...   en

[3 rows x 13 columns]

In [12]:
df2.shape

(72312, 8)

In [13]:
df1.shape

(3047, 13)

In [14]:
def find_total_events(df1_row):
  total_likes = df2[(df2["contentId"] == df1_row["contentId"]) & (df2["eventType"] == "LIKE")].shape[0]
  total_views = df2[(df2["contentId"] == df1_row["contentId"]) & (df2["eventType"] == "VIEW")].shape[0]
  total_bookmarks = df2[(df2["contentId"] == df1_row["contentId"]) & (df2["eventType"] == "BOOKMARK")].shape[0]
  total_follows = df2[(df2["contentId"] == df1_row["contentId"]) & (df2["eventType"] == "FOLLOW")].shape[0]
  total_comments = df2[(df2["contentId"] == df1_row["contentId"]) & (df2["eventType"] == "COMMENT CREATED")].shape[0]
  return total_likes + total_views + total_bookmarks + total_follows + total_comments

df1["total_events"] = df1.apply(find_total_events, axis=1)
df1.head(3)

    timestamp       eventType  ...  lang  total_events
1  1459193988  CONTENT SHARED  ...    en             1
2  1459194146  CONTENT SHARED  ...    en             1
3  1459194474  CONTENT SHARED  ...    en            13

[3 rows x 14 columns]

In [15]:
df1 = df1.sort_values(['total_events'], ascending=[False])
df1.head(3)

       timestamp       eventType  ...  lang  total_events
3096  1487246811  CONTENT SHARED  ...    en           433
1671  1467813728  CONTENT SHARED  ...    pt           315
1814  1468867647  CONTENT SHARED  ...    pt           294

[3 rows x 14 columns]